[package]
name = "vvscode"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"
ropey = "1.6.1"
core-text = "=21.0.0" # caused by text-core updated, gpui has outdated version https://github.com/zed-industries/zed/issues/46966
